# Generated by Django 5.2.1 on 2025-05-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosusuario',
            name='ciudad_de_residencia',
        ),
        migrations.RemoveField(
            model_name='datosusuario',
            name='modalidad_evento',
        ),
        migrations.RemoveField(
            model_name='datosusuario',
            name='país_de_residencia',
        ),
        migrations.RemoveField(
            model_name='datosusuario',
            name='tipo_evento',
        ),
    ]
