# Generated by Django 5.2.1 on 2025-05-22 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_remove_datosusuario_ciudad_de_residencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosusuario',
            old_name='areas_bienestar',
            new_name='AreasBienestar',
        ),
        migrations.RenameField(
            model_name='datosusuario',
            old_name='año_de_graduacion',
            new_name='AñoGraduacion',
        ),
        migrations.RenameField(
            model_name='datosusuario',
            old_name='nombre_completo',
            new_name='NombreCompleto',
        ),
        migrations.RenameField(
            model_name='datosusuario',
            old_name='otras_actividades',
            new_name='OtrasActividades',
        ),
        migrations.RenameField(
            model_name='datosusuario',
            old_name='temas_eventos',
            new_name='TemasEventos',
        ),
        migrations.RenameField(
            model_name='datosusuario',
            old_name='cédula',
            new_name='cedula',
        ),
    ]
