# Generated by Django 5.2.1 on 2025-05-22 21:30

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_rename_areas_bienestar_datosusuario_areasbienestar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuario',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datosusuario',
            name='pais',
            field=django_countries.fields.CountryField(default='CO', max_length=2),
            preserve_default=False,
        ),
    ]
