# Generated by Django 5.2.1 on 2025-05-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_datosusuario_ciudad_datosusuario_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuario',
            name='AreasBienestar',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='TemasEventos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='programa',
            field=models.CharField(choices=[('Administración de Empresas', 'Administración de Empresas'), ('Administración de Mercadeo', 'Administración de Mercadeo'), ('Administración de Negocios Internacionales', 'Administración de Negocios Internacionales'), ('Administración de Obras Civiles', 'Administración de Obras Civiles'), ('Administración Turística y Hotelera', 'Administración Turística y Hotelera'), ('Derecho', 'Derecho'), ('Especialización en Gerencia de Mercadeo', 'Especialización en Gerencia de Mercadeo'), ('Especialización en gerencia del talento Humano', 'Especialización en gerencia del talento Humano'), ('Especialización en Evaluación y Gerencia de Proyectos', 'Especialización en Evaluación y Gerencia de Proyectos'), ('Especialización en Rehabilitación Cardiopulmonar', 'Especialización en Rehabilitación Cardiopulmonar'), ('Especialización de Sanidad Animal', 'Especialización de Sanidad Animal'), ('Ingeniería Administrativa', 'Ingeniería Administrativa'), ('Ingeniería de software', 'Ingeniería de software'), ('Medicina', 'Medicina'), ('Medicina Veterinaria y Zootecnia', 'Medicina Veterinaria y Zootecnia'), ('Odontología', 'Odontología'), ('Profesional en Mercadeo y Publicidad', 'Profesional en Mercadeo y Publicidad'), ('Tecnología en Gestión Empresarial', 'Tecnología en Gestión Empresarial'), ('Tecnología en Laboratorio de Prótesis Dental', 'Tecnología en Laboratorio de Prótesis Dental'), ('Terapia Respiratoria', 'Terapia Respiratoria')], max_length=100),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='sede',
            field=models.CharField(choices=[('Medellín', 'Medellín'), ('Pereira', 'Pereira'), ('Centro Tutorial Rionegro', 'Centro Tutorial Rionegro'), ('Centro Tutorial Apartadó', 'Centro Tutorial Apartadó')], max_length=100),
        ),
    ]
