# Generated by Django 5.2.1 on 2025-05-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_alter_datosusuario_areasbienestar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_egresados/')),
            ],
        ),
    ]
