# Generated by Django 5.2.1 on 2025-05-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0006_datosusuario_fecha_actualizacion'),
        ('formulario', '0006_imagenformulario'),
    ]

    operations = [
    ]
